/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * ViralForge API specification
 * OpenAPI spec version: 0.1.0
 */

export interface AccessCode {
  id: number;
  code: string;
  /** @nullable */
  label: string | null;
  grantUnlimited: boolean;
  bonusCredits: number;
  maxUses: number;
  usedCount: number;
  /** @nullable */
  expiresAt: Date | null;
  createdAt: Date;
}
