/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * ViralForge API specification
 * OpenAPI spec version: 0.1.0
 */
import type { Market } from "./market";

export interface AddCustomVoiceRequest {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  voiceId: string;
  market: Market;
  /** @nullable */
  description?: string | null;
}
