/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * ViralForge API specification
 * OpenAPI spec version: 0.1.0
 */

export interface AdminUser {
  id: string;
  /** @nullable */
  email: string | null;
  /** @nullable */
  firstName: string | null;
  /** @nullable */
  lastName: string | null;
  createdAt: Date;
  isOwner: boolean;
  unlimited: boolean;
  /** @nullable */
  unlimitedSource: string | null;
}
