/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * ViralForge API specification
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface AuthUser {
  id: string;
  /** @nullable */
  email: string | null;
  /** @nullable */
  firstName: string | null;
  /** @nullable */
  lastName: string | null;
  /** @nullable */
  profileImageUrl: string | null;
}

export interface AuthUserEnvelope {
  user: AuthUser | null;
}

export interface MobileTokenExchangeRequest {
  /** @minLength 1 */
  code: string;
  /** @minLength 1 */
  code_verifier: string;
  /** @minLength 1 */
  redirect_uri: string;
  /** @minLength 1 */
  state: string;
  /** @minLength 1 */
  nonce?: string;
}

export interface MobileTokenExchangeSuccess {
  token: string;
}

export const LogoutSuccessValue = {
  success: true,
} as const;
export type LogoutSuccess = typeof LogoutSuccessValue;

export interface ErrorEnvelope {
  error: string;
}

export interface CreditError {
  error: string;
  /** @nullable */
  lockedUntil: string | null;
  creditsRemaining: number;
}

export type Market = (typeof Market)[keyof typeof Market];

export const Market = {
  india: "india",
  usa: "usa",
  uk: "uk",
  global: "global",
} as const;

export interface MeProfile {
  id: string;
  /** @nullable */
  email: string | null;
  /** @nullable */
  firstName: string | null;
  /** @nullable */
  lastName: string | null;
  /** @nullable */
  profileImageUrl: string | null;
  creditsRemaining: number;
  totalCreditsUsed: number;
  /** @nullable */
  lockedUntil: string | null;
  shareBonusesClaimed: number;
  isOwner: boolean;
  unlimited: boolean;
  /** @nullable */
  unlimitedSource: string | null;
  hasCustomElevenlabsKey: boolean;
  xp: number;
  level: number;
  xpToNextLevel: number;
  streak: number;
  bestScore: number;
}

export interface IntegrationStatus {
  openai: boolean;
  pexels: boolean;
  elevenlabs: boolean;
}

export type BuildType = (typeof BuildType)[keyof typeof BuildType];

export const BuildType = {
  reel: "reel",
  long: "long",
  audio: "audio",
} as const;

export type BuildTone = (typeof BuildTone)[keyof typeof BuildTone];

export const BuildTone = {
  cinematic: "cinematic",
  friendly: "friendly",
  "high-energy": "high-energy",
  authoritative: "authoritative",
  storytelling: "storytelling",
  comedic: "comedic",
} as const;

export type BuildLength = (typeof BuildLength)[keyof typeof BuildLength];

export const BuildLength = {
  short: "short",
  medium: "medium",
  long: "long",
  podcast: "podcast",
} as const;

export interface BuildOptions {
  chapters?: boolean;
  monetize?: boolean;
  broll?: boolean;
}

export interface GenerateScriptRequest {
  /** @minLength 1 */
  prompt: string;
  market: Market;
  /** @nullable */
  niche?: string | null;
  /**
   * @minimum 15
   * @maximum 90
   * @nullable
   */
  targetSeconds?: number | null;
  buildType?: BuildType;
  tone?: BuildTone;
  length?: BuildLength;
  options?: BuildOptions;
}

export interface Scene {
  order: number;
  narration: string;
  keywords: string[];
}

export interface ScriptGeneration {
  title: string;
  hook: string;
  fullScript: string;
  scenes: Scene[];
  hashtags: string[];
  market: Market;
  creditsRemaining: number;
  /** @nullable */
  lockedUntil: string | null;
  /** @nullable */
  chapters?: string[] | null;
  /** @nullable */
  bRollIdeas?: string[] | null;
  /** @nullable */
  monetizationTips?: string[] | null;
  /**
   * @minimum 0
   * @maximum 100
   */
  qualityScore?: number;
  buildType?: BuildType;
  tone?: BuildTone;
  length?: BuildLength;
  xpAwarded?: number;
  levelUp?: boolean;
  bonusCreditsGranted?: number;
  newLevel?: number;
  streak?: number;
}

export type QuestDifficulty =
  (typeof QuestDifficulty)[keyof typeof QuestDifficulty];

export const QuestDifficulty = {
  easy: "easy",
  medium: "medium",
  hard: "hard",
} as const;

export interface Quest {
  id: number;
  title: string;
  description: string;
  /** @nullable */
  niche: string | null;
  difficulty: QuestDifficulty;
  xpReward: number;
  isCompleted: boolean;
  /** @nullable */
  completedAt: string | null;
  createdAt: string;
}

export interface GameStats {
  xp: number;
  level: number;
  xpToNextLevel: number;
  streak: number;
  bestScore: number;
  /** @nullable */
  lastBuildDate: string | null;
}

export interface QuestListPayload {
  quests: Quest[];
  stats: GameStats;
}

export interface CreateQuestRequest {
  /** @nullable */
  niche?: string | null;
  difficulty?: QuestDifficulty;
  /**
   * @minimum 1
   * @maximum 5
   * @nullable
   */
  count?: number | null;
}

export interface CreatedQuestsBatch {
  quests: Quest[];
}

export interface QuestReward {
  xpAwarded: number;
  levelUp: boolean;
  bonusCreditsGranted: number;
}

export interface QuestCompletionResult {
  quest: Quest;
  reward: QuestReward;
  stats: GameStats;
}

export interface QuestsResetResult {
  ok: boolean;
}

export interface RewriteScriptRequest {
  /** @minLength 1 */
  script: string;
  /** @minLength 1 */
  instruction: string;
  market: Market;
}

export interface RewriteResult {
  script: string;
}

export interface PexelsSearchRequest {
  keywords: string[];
  /**
   * @minimum 1
   * @maximum 5
   * @nullable
   */
  perKeyword?: number | null;
}

export interface PexelsClip {
  id: string;
  keyword: string;
  videoUrl: string;
  thumbnailUrl: string;
  durationSeconds: number;
  width: number;
  height: number;
}

export interface PexelsSearchResponse {
  clips: PexelsClip[];
}

export interface Voice {
  id: string;
  name: string;
  accent: string;
  market: Market;
  description: string;
  /** @nullable */
  previewUrl: string | null;
  isCustom: boolean;
}

export interface VoicesResponse {
  voices: Voice[];
}

export interface SynthesizeRequest {
  /** @minLength 1 */
  text: string;
  /** @minLength 1 */
  voiceId: string;
}

export interface SynthesizeResponse {
  audioUrl: string;
  durationSeconds: number;
}

export type RenderClipInputKind =
  (typeof RenderClipInputKind)[keyof typeof RenderClipInputKind];

export const RenderClipInputKind = {
  pexels: "pexels",
  upload: "upload",
  image: "image",
} as const;

export interface RenderClipInput {
  url: string;
  kind: RenderClipInputKind;
  /** @nullable */
  durationSeconds?: number | null;
}

export interface RenderRequest {
  title: string;
  market: Market;
  script: string;
  audioUrl: string;
  /** @nullable */
  voiceName?: string | null;
  clips: RenderClipInput[];
}

export interface RenderResponse {
  historyId: number;
  mp4Url: string;
  thumbnailUrl: string;
  durationSeconds: number;
}

export interface HistoryItem {
  id: number;
  title: string;
  market: Market;
  script: string;
  mp4Url: string;
  thumbnailUrl: string;
  durationSeconds: number;
  createdAt: string;
}

export interface HistoryListResponse {
  items: HistoryItem[];
}

export interface RedeemCodeRequest {
  /** @minLength 1 */
  code: string;
}

export interface RedeemCodeResponse {
  ok: boolean;
  alreadyRedeemed: boolean;
  grantUnlimited: boolean;
  bonusCredits: number;
}

export interface CustomVoice {
  id: number;
  name: string;
  voiceId: string;
  market: Market;
  /** @nullable */
  description: string | null;
  createdAt: string;
}

export interface CustomVoiceListResponse {
  voices: CustomVoice[];
}

export interface AddCustomVoiceRequest {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  voiceId: string;
  market: Market;
  /** @nullable */
  description?: string | null;
}

export interface ElevenlabsKeyStatus {
  hasKey: boolean;
}

export interface SetElevenlabsKeyRequest {
  /** @nullable */
  apiKey: string | null;
}

export interface AccessCode {
  id: number;
  code: string;
  /** @nullable */
  label: string | null;
  grantUnlimited: boolean;
  bonusCredits: number;
  maxUses: number;
  usedCount: number;
  /** @nullable */
  expiresAt: string | null;
  createdAt: string;
}

export interface AccessCodeListResponse {
  codes: AccessCode[];
}

export interface CreateAccessCodeRequest {
  /** @nullable */
  label?: string | null;
  /** @nullable */
  grantUnlimited?: boolean | null;
  /**
   * @minimum 0
   * @maximum 500
   * @nullable
   */
  bonusCredits?: number | null;
  /**
   * @minimum 1
   * @maximum 10000
   * @nullable
   */
  maxUses?: number | null;
  /** @nullable */
  expiresAt?: string | null;
}

export interface AdminUser {
  id: string;
  /** @nullable */
  email: string | null;
  /** @nullable */
  firstName: string | null;
  /** @nullable */
  lastName: string | null;
  createdAt: string;
  isOwner: boolean;
  unlimited: boolean;
  /** @nullable */
  unlimitedSource: string | null;
}

export interface AdminUserListResponse {
  users: AdminUser[];
}

/**
 * Opaque session token — `Bearer <sid>`.
 */
export type AuthorizationSessionHeaderParameter = string;

export type BeginBrowserLoginParams = {
  returnTo?: string;
};

export type HandleBrowserLoginCallbackParams = {
  code?: string;
  state?: string;
  iss?: string;
};

export type ListVoicesParams = {
  market?: Market;
};
