/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * ViralForge API specification
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary Get the currently authenticated user
 */
export const GetCurrentAuthUserHeader = zod.object({
  Authorization: zod
    .string()
    .optional()
    .describe("Opaque session token — `Bearer <sid>`."),
});

export const GetCurrentAuthUserResponse = zod.object({
  user: zod.union([
    zod.object({
      id: zod.string(),
      email: zod.string().email().nullable(),
      firstName: zod.string().nullable(),
      lastName: zod.string().nullable(),
      profileImageUrl: zod.string().nullable(),
    }),
    zod.null(),
  ]),
});

/**
 * @summary Start the browser OIDC login flow
 */
export const BeginBrowserLoginQueryParams = zod.object({
  returnTo: zod.coerce.string().optional(),
});

/**
 * @summary Complete the browser OIDC login flow
 */
export const HandleBrowserLoginCallbackQueryParams = zod.object({
  code: zod.coerce.string().optional(),
  state: zod.coerce.string().optional(),
  iss: zod.coerce.string().url().optional(),
});

/**
 * @summary Clear the session and begin OIDC logout
 */
export const LogoutBrowserSessionHeader = zod.object({
  Authorization: zod
    .string()
    .optional()
    .describe("Opaque session token — `Bearer <sid>`."),
});

/**
 * @summary Exchange a mobile OIDC code for a session token
 */

export const ExchangeMobileAuthorizationCodeBody = zod.object({
  code: zod.string().min(1),
  code_verifier: zod.string().min(1),
  redirect_uri: zod.string().url().min(1),
  state: zod.string().min(1),
  nonce: zod.string().min(1).optional(),
});

export const ExchangeMobileAuthorizationCodeResponse = zod.object({
  token: zod.string(),
});

/**
 * @summary Delete a mobile session token
 */
export const LogoutMobileSessionHeader = zod.object({
  Authorization: zod
    .string()
    .optional()
    .describe("Opaque session token — `Bearer <sid>`."),
});

export const LogoutMobileSessionResponse = zod.object({
  success: zod.boolean(),
});

/**
 * @summary Get the current user profile with credits and lock state
 */
export const GetMeResponse = zod.object({
  id: zod.string(),
  email: zod.string().email().nullable(),
  firstName: zod.string().nullable(),
  lastName: zod.string().nullable(),
  profileImageUrl: zod.string().nullable(),
  creditsRemaining: zod.number(),
  totalCreditsUsed: zod.number(),
  lockedUntil: zod.coerce.date().nullable(),
  shareBonusesClaimed: zod.number(),
  isOwner: zod.boolean(),
  unlimited: zod.boolean(),
  unlimitedSource: zod.string().nullable(),
  hasCustomElevenlabsKey: zod.boolean(),
  xp: zod.number(),
  level: zod.number(),
  xpToNextLevel: zod.number(),
  streak: zod.number(),
  bestScore: zod.number(),
});

/**
 * @summary Claim a +1 credit bonus for sharing on WhatsApp
 */
export const ClaimShareBonusResponse = zod.object({
  id: zod.string(),
  email: zod.string().email().nullable(),
  firstName: zod.string().nullable(),
  lastName: zod.string().nullable(),
  profileImageUrl: zod.string().nullable(),
  creditsRemaining: zod.number(),
  totalCreditsUsed: zod.number(),
  lockedUntil: zod.coerce.date().nullable(),
  shareBonusesClaimed: zod.number(),
  isOwner: zod.boolean(),
  unlimited: zod.boolean(),
  unlimitedSource: zod.string().nullable(),
  hasCustomElevenlabsKey: zod.boolean(),
  xp: zod.number(),
  level: zod.number(),
  xpToNextLevel: zod.number(),
  streak: zod.number(),
  bestScore: zod.number(),
});

/**
 * @summary Check which third-party integrations are configured
 */
export const GetIntegrationStatusResponse = zod.object({
  openai: zod.boolean(),
  pexels: zod.boolean(),
  elevenlabs: zod.boolean(),
});

/**
 * @summary Generate a market-aware video script (consumes 1 credit)
 */

export const generateScriptBodyTargetSecondsMin = 15;
export const generateScriptBodyTargetSecondsMax = 90;

export const GenerateScriptBody = zod.object({
  prompt: zod.string().min(1),
  market: zod.enum(["india", "usa", "uk", "global"]),
  niche: zod.string().nullish(),
  targetSeconds: zod
    .number()
    .min(generateScriptBodyTargetSecondsMin)
    .max(generateScriptBodyTargetSecondsMax)
    .nullish(),
  buildType: zod.enum(["reel", "long", "audio"]).optional(),
  tone: zod
    .enum([
      "cinematic",
      "friendly",
      "high-energy",
      "authoritative",
      "storytelling",
      "comedic",
    ])
    .optional(),
  length: zod.enum(["short", "medium", "long", "podcast"]).optional(),
  options: zod
    .object({
      chapters: zod.boolean().optional(),
      monetize: zod.boolean().optional(),
      broll: zod.boolean().optional(),
    })
    .optional(),
});

export const generateScriptResponseQualityScoreMin = 0;
export const generateScriptResponseQualityScoreMax = 100;

export const GenerateScriptResponse = zod.object({
  title: zod.string(),
  hook: zod.string(),
  fullScript: zod.string(),
  scenes: zod.array(
    zod.object({
      order: zod.number(),
      narration: zod.string(),
      keywords: zod.array(zod.string()),
    }),
  ),
  hashtags: zod.array(zod.string()),
  market: zod.enum(["india", "usa", "uk", "global"]),
  creditsRemaining: zod.number(),
  lockedUntil: zod.coerce.date().nullable(),
  chapters: zod.array(zod.string()).nullish(),
  bRollIdeas: zod.array(zod.string()).nullish(),
  monetizationTips: zod.array(zod.string()).nullish(),
  qualityScore: zod
    .number()
    .min(generateScriptResponseQualityScoreMin)
    .max(generateScriptResponseQualityScoreMax)
    .optional(),
  buildType: zod.enum(["reel", "long", "audio"]).optional(),
  tone: zod
    .enum([
      "cinematic",
      "friendly",
      "high-energy",
      "authoritative",
      "storytelling",
      "comedic",
    ])
    .optional(),
  length: zod.enum(["short", "medium", "long", "podcast"]).optional(),
  xpAwarded: zod.number().optional(),
  levelUp: zod.boolean().optional(),
  bonusCreditsGranted: zod.number().optional(),
  newLevel: zod.number().optional(),
  streak: zod.number().optional(),
});

/**
 * @summary Rewrite an existing script based on user feedback
 */

export const RewriteScriptBody = zod.object({
  script: zod.string().min(1),
  instruction: zod.string().min(1),
  market: zod.enum(["india", "usa", "uk", "global"]),
});

export const RewriteScriptResponse = zod.object({
  script: zod.string(),
});

/**
 * @summary Search Pexels for short stock video clips
 */
export const searchPexelsClipsBodyPerKeywordMax = 5;

export const SearchPexelsClipsBody = zod.object({
  keywords: zod.array(zod.string()),
  perKeyword: zod
    .number()
    .min(1)
    .max(searchPexelsClipsBodyPerKeywordMax)
    .nullish(),
});

export const SearchPexelsClipsResponse = zod.object({
  clips: zod.array(
    zod.object({
      id: zod.string(),
      keyword: zod.string(),
      videoUrl: zod.string(),
      thumbnailUrl: zod.string(),
      durationSeconds: zod.number(),
      width: zod.number(),
      height: zod.number(),
    }),
  ),
});

/**
 * @summary List available voices, optionally filtered by market
 */
export const ListVoicesQueryParams = zod.object({
  market: zod.enum(["india", "usa", "uk", "global"]).optional(),
});

export const ListVoicesResponse = zod.object({
  voices: zod.array(
    zod.object({
      id: zod.string(),
      name: zod.string(),
      accent: zod.string(),
      market: zod.enum(["india", "usa", "uk", "global"]),
      description: zod.string(),
      previewUrl: zod.string().nullable(),
      isCustom: zod.boolean(),
    }),
  ),
});

/**
 * @summary Generate voiceover audio from text using a selected voice
 */

export const SynthesizeVoiceBody = zod.object({
  text: zod.string().min(1),
  voiceId: zod.string().min(1),
});

export const SynthesizeVoiceResponse = zod.object({
  audioUrl: zod.string(),
  durationSeconds: zod.number(),
});

/**
 * @summary Render the final 1080p MP4 from script, voice, and clips
 */
export const RenderVideoBody = zod.object({
  title: zod.string(),
  market: zod.enum(["india", "usa", "uk", "global"]),
  script: zod.string(),
  audioUrl: zod.string(),
  voiceName: zod.string().nullish(),
  clips: zod.array(
    zod.object({
      url: zod.string(),
      kind: zod.enum(["pexels", "upload", "image"]),
      durationSeconds: zod.number().nullish(),
    }),
  ),
});

export const RenderVideoResponse = zod.object({
  historyId: zod.number(),
  mp4Url: zod.string(),
  thumbnailUrl: zod.string(),
  durationSeconds: zod.number(),
});

/**
 * @summary Redeem an access code for unlimited or bonus credits
 */

export const RedeemAccessCodeBody = zod.object({
  code: zod.string().min(1),
});

export const RedeemAccessCodeResponse = zod.object({
  ok: zod.boolean(),
  alreadyRedeemed: zod.boolean(),
  grantUnlimited: zod.boolean(),
  bonusCredits: zod.number(),
});

/**
 * @summary List the current user's custom voices
 */
export const ListCustomVoicesResponse = zod.object({
  voices: zod.array(
    zod.object({
      id: zod.number(),
      name: zod.string(),
      voiceId: zod.string(),
      market: zod.enum(["india", "usa", "uk", "global"]),
      description: zod.string().nullable(),
      createdAt: zod.coerce.date(),
    }),
  ),
});

/**
 * @summary Add a custom ElevenLabs voice ID for the current user
 */

export const AddCustomVoiceBody = zod.object({
  name: zod.string().min(1),
  voiceId: zod.string().min(1),
  market: zod.enum(["india", "usa", "uk", "global"]),
  description: zod.string().nullish(),
});

export const AddCustomVoiceResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  voiceId: zod.string(),
  market: zod.enum(["india", "usa", "uk", "global"]),
  description: zod.string().nullable(),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Remove a custom voice
 */
export const DeleteCustomVoiceParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary Check whether the current user has set a personal ElevenLabs key
 */
export const GetElevenlabsKeyStatusResponse = zod.object({
  hasKey: zod.boolean(),
});

/**
 * @summary Set or clear the current user's personal ElevenLabs API key
 */
export const SetElevenlabsKeyBody = zod.object({
  apiKey: zod.string().nullable(),
});

export const SetElevenlabsKeyResponse = zod.object({
  hasKey: zod.boolean(),
});

/**
 * @summary Owner-only list of all access codes
 */
export const ListAccessCodesResponse = zod.object({
  codes: zod.array(
    zod.object({
      id: zod.number(),
      code: zod.string(),
      label: zod.string().nullable(),
      grantUnlimited: zod.boolean(),
      bonusCredits: zod.number(),
      maxUses: zod.number(),
      usedCount: zod.number(),
      expiresAt: zod.coerce.date().nullable(),
      createdAt: zod.coerce.date(),
    }),
  ),
});

/**
 * @summary Owner-only — mint a new access code
 */
export const createAccessCodeBodyBonusCreditsMin = 0;
export const createAccessCodeBodyBonusCreditsMax = 500;

export const createAccessCodeBodyMaxUsesMax = 10000;

export const CreateAccessCodeBody = zod.object({
  label: zod.string().nullish(),
  grantUnlimited: zod.boolean().nullish(),
  bonusCredits: zod
    .number()
    .min(createAccessCodeBodyBonusCreditsMin)
    .max(createAccessCodeBodyBonusCreditsMax)
    .nullish(),
  maxUses: zod.number().min(1).max(createAccessCodeBodyMaxUsesMax).nullish(),
  expiresAt: zod.coerce.date().nullish(),
});

export const CreateAccessCodeResponse = zod.object({
  id: zod.number(),
  code: zod.string(),
  label: zod.string().nullable(),
  grantUnlimited: zod.boolean(),
  bonusCredits: zod.number(),
  maxUses: zod.number(),
  usedCount: zod.number(),
  expiresAt: zod.coerce.date().nullable(),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Owner-only delete
 */
export const DeleteAccessCodeParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary Owner-only list of users
 */
export const ListAdminUsersResponse = zod.object({
  users: zod.array(
    zod.object({
      id: zod.string(),
      email: zod.string().nullable(),
      firstName: zod.string().nullable(),
      lastName: zod.string().nullable(),
      createdAt: zod.coerce.date(),
      isOwner: zod.boolean(),
      unlimited: zod.boolean(),
      unlimitedSource: zod.string().nullable(),
    }),
  ),
});

/**
 * @summary List the current user's quests with game stats
 */
export const ListQuestsResponse = zod.object({
  quests: zod.array(
    zod.object({
      id: zod.number(),
      title: zod.string(),
      description: zod.string(),
      niche: zod.string().nullable(),
      difficulty: zod.enum(["easy", "medium", "hard"]),
      xpReward: zod.number(),
      isCompleted: zod.boolean(),
      completedAt: zod.coerce.date().nullable(),
      createdAt: zod.coerce.date(),
    }),
  ),
  stats: zod.object({
    xp: zod.number(),
    level: zod.number(),
    xpToNextLevel: zod.number(),
    streak: zod.number(),
    bestScore: zod.number(),
    lastBuildDate: zod.string().nullable(),
  }),
});

/**
 * @summary Generate one or more new quests
 */
export const createQuestBodyCountMax = 5;

export const CreateQuestBody = zod.object({
  niche: zod.string().nullish(),
  difficulty: zod.enum(["easy", "medium", "hard"]).optional(),
  count: zod.number().min(1).max(createQuestBodyCountMax).nullish(),
});

export const CreateQuestResponse = zod.object({
  quests: zod.array(
    zod.object({
      id: zod.number(),
      title: zod.string(),
      description: zod.string(),
      niche: zod.string().nullable(),
      difficulty: zod.enum(["easy", "medium", "hard"]),
      xpReward: zod.number(),
      isCompleted: zod.boolean(),
      completedAt: zod.coerce.date().nullable(),
      createdAt: zod.coerce.date(),
    }),
  ),
});

/**
 * @summary Wipe all quests for the current user
 */
export const ResetQuestsResponse = zod.object({
  ok: zod.boolean(),
});

/**
 * @summary Mark a quest complete and award XP
 */
export const CompleteQuestParams = zod.object({
  id: zod.coerce.number(),
});

export const CompleteQuestResponse = zod.object({
  quest: zod.object({
    id: zod.number(),
    title: zod.string(),
    description: zod.string(),
    niche: zod.string().nullable(),
    difficulty: zod.enum(["easy", "medium", "hard"]),
    xpReward: zod.number(),
    isCompleted: zod.boolean(),
    completedAt: zod.coerce.date().nullable(),
    createdAt: zod.coerce.date(),
  }),
  reward: zod.object({
    xpAwarded: zod.number(),
    levelUp: zod.boolean(),
    bonusCreditsGranted: zod.number(),
  }),
  stats: zod.object({
    xp: zod.number(),
    level: zod.number(),
    xpToNextLevel: zod.number(),
    streak: zod.number(),
    bestScore: zod.number(),
    lastBuildDate: zod.string().nullable(),
  }),
});

/**
 * @summary List the current user's past video generations
 */
export const ListHistoryResponse = zod.object({
  items: zod.array(
    zod.object({
      id: zod.number(),
      title: zod.string(),
      market: zod.enum(["india", "usa", "uk", "global"]),
      script: zod.string(),
      mp4Url: zod.string(),
      thumbnailUrl: zod.string(),
      durationSeconds: zod.number(),
      createdAt: zod.coerce.date(),
    }),
  ),
});

/**
 * @summary Get a single history item
 */
export const GetHistoryItemParams = zod.object({
  id: zod.coerce.number(),
});

export const GetHistoryItemResponse = zod.object({
  id: zod.number(),
  title: zod.string(),
  market: zod.enum(["india", "usa", "uk", "global"]),
  script: zod.string(),
  mp4Url: zod.string(),
  thumbnailUrl: zod.string(),
  durationSeconds: zod.number(),
  createdAt: zod.coerce.date(),
});

/**
 * @summary Delete a history item
 */
export const DeleteHistoryItemParams = zod.object({
  id: zod.coerce.number(),
});
