/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * ViralForge API specification
 * OpenAPI spec version: 0.1.0
 */

export type BuildTone = (typeof BuildTone)[keyof typeof BuildTone];

export const BuildTone = {
  cinematic: "cinematic",
  friendly: "friendly",
  "high-energy": "high-energy",
  authoritative: "authoritative",
  storytelling: "storytelling",
  comedic: "comedic",
} as const;
