/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * ViralForge API specification
 * OpenAPI spec version: 0.1.0
 */
import type { QuestDifficulty } from "./questDifficulty";

export interface CreateQuestRequest {
  /** @nullable */
  niche?: string | null;
  difficulty?: QuestDifficulty;
  /**
   * @minimum 1
   * @maximum 5
   * @nullable
   */
  count?: number | null;
}
