/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * ViralForge API specification
 * OpenAPI spec version: 0.1.0
 */

export interface CreateAccessCodeRequest {
  /** @nullable */
  label?: string | null;
  /** @nullable */
  grantUnlimited?: boolean | null;
  /**
   * @minimum 0
   * @maximum 500
   * @nullable
   */
  bonusCredits?: number | null;
  /**
   * @minimum 1
   * @maximum 10000
   * @nullable
   */
  maxUses?: number | null;
  /** @nullable */
  expiresAt?: Date | null;
}
