/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * ViralForge API specification
 * OpenAPI spec version: 0.1.0
 */
import type { BuildLength } from "./buildLength";
import type { BuildOptions } from "./buildOptions";
import type { BuildTone } from "./buildTone";
import type { BuildType } from "./buildType";
import type { Market } from "./market";

export interface GenerateScriptRequest {
  /** @minLength 1 */
  prompt: string;
  market: Market;
  /** @nullable */
  niche?: string | null;
  /**
   * @minimum 15
   * @maximum 90
   * @nullable
   */
  targetSeconds?: number | null;
  buildType?: BuildType;
  tone?: BuildTone;
  length?: BuildLength;
  options?: BuildOptions;
}
