/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * ViralForge API specification
 * OpenAPI spec version: 0.1.0
 */
import type { Market } from "./market";

export interface HistoryItem {
  id: number;
  title: string;
  market: Market;
  script: string;
  mp4Url: string;
  thumbnailUrl: string;
  durationSeconds: number;
  createdAt: Date;
}
