/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * ViralForge API specification
 * OpenAPI spec version: 0.1.0
 */

export type Market = (typeof Market)[keyof typeof Market];

export const Market = {
  india: "india",
  usa: "usa",
  uk: "uk",
  global: "global",
} as const;
