/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * ViralForge API specification
 * OpenAPI spec version: 0.1.0
 */

export interface MeProfile {
  id: string;
  /** @nullable */
  email: string | null;
  /** @nullable */
  firstName: string | null;
  /** @nullable */
  lastName: string | null;
  /** @nullable */
  profileImageUrl: string | null;
  creditsRemaining: number;
  totalCreditsUsed: number;
  /** @nullable */
  lockedUntil: Date | null;
  shareBonusesClaimed: number;
  isOwner: boolean;
  unlimited: boolean;
  /** @nullable */
  unlimitedSource: string | null;
  hasCustomElevenlabsKey: boolean;
  xp: number;
  level: number;
  xpToNextLevel: number;
  streak: number;
  bestScore: number;
}
