/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * ViralForge API specification
 * OpenAPI spec version: 0.1.0
 */
import type { PexelsClip } from "./pexelsClip";

export interface PexelsSearchResponse {
  clips: PexelsClip[];
}
