/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * ViralForge API specification
 * OpenAPI spec version: 0.1.0
 */

export interface PexelsSearchRequest {
  keywords: string[];
  /**
   * @minimum 1
   * @maximum 5
   * @nullable
   */
  perKeyword?: number | null;
}
