/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * ViralForge API specification
 * OpenAPI spec version: 0.1.0
 */

export interface PexelsClip {
  id: string;
  keyword: string;
  videoUrl: string;
  thumbnailUrl: string;
  durationSeconds: number;
  width: number;
  height: number;
}
