/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * ViralForge API specification
 * OpenAPI spec version: 0.1.0
 */
import type { QuestDifficulty } from "./questDifficulty";

export interface Quest {
  id: number;
  title: string;
  description: string;
  /** @nullable */
  niche: string | null;
  difficulty: QuestDifficulty;
  xpReward: number;
  isCompleted: boolean;
  /** @nullable */
  completedAt: Date | null;
  createdAt: Date;
}
