/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * ViralForge API specification
 * OpenAPI spec version: 0.1.0
 */
import type { GameStats } from "./gameStats";
import type { Quest } from "./quest";
import type { QuestReward } from "./questReward";

export interface QuestCompletionResult {
  quest: Quest;
  reward: QuestReward;
  stats: GameStats;
}
