/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * ViralForge API specification
 * OpenAPI spec version: 0.1.0
 */

export type RenderClipInputKind =
  (typeof RenderClipInputKind)[keyof typeof RenderClipInputKind];

export const RenderClipInputKind = {
  pexels: "pexels",
  upload: "upload",
  image: "image",
} as const;
