/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * ViralForge API specification
 * OpenAPI spec version: 0.1.0
 */
import type { Market } from "./market";
import type { RenderClipInput } from "./renderClipInput";

export interface RenderRequest {
  title: string;
  market: Market;
  script: string;
  audioUrl: string;
  /** @nullable */
  voiceName?: string | null;
  clips: RenderClipInput[];
}
