/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * ViralForge API specification
 * OpenAPI spec version: 0.1.0
 */
import type { Market } from "./market";

export interface RewriteScriptRequest {
  /** @minLength 1 */
  script: string;
  /** @minLength 1 */
  instruction: string;
  market: Market;
}
