/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * ViralForge API specification
 * OpenAPI spec version: 0.1.0
 */
import type { BuildLength } from "./buildLength";
import type { BuildTone } from "./buildTone";
import type { BuildType } from "./buildType";
import type { Market } from "./market";
import type { Scene } from "./scene";

export interface ScriptGeneration {
  title: string;
  hook: string;
  fullScript: string;
  scenes: Scene[];
  hashtags: string[];
  market: Market;
  creditsRemaining: number;
  /** @nullable */
  lockedUntil: Date | null;
  /** @nullable */
  chapters?: string[] | null;
  /** @nullable */
  bRollIdeas?: string[] | null;
  /** @nullable */
  monetizationTips?: string[] | null;
  /**
   * @minimum 0
   * @maximum 100
   */
  qualityScore?: number;
  buildType?: BuildType;
  tone?: BuildTone;
  length?: BuildLength;
  xpAwarded?: number;
  levelUp?: boolean;
  bonusCreditsGranted?: number;
  newLevel?: number;
  streak?: number;
}
