/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * ViralForge API specification
 * OpenAPI spec version: 0.1.0
 */

export interface SynthesizeRequest {
  /** @minLength 1 */
  text: string;
  /** @minLength 1 */
  voiceId: string;
}
