/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * ViralForge API specification
 * OpenAPI spec version: 0.1.0
 */
import type { Market } from "./market";

export interface Voice {
  id: string;
  name: string;
  accent: string;
  market: Market;
  description: string;
  /** @nullable */
  previewUrl: string | null;
  isCustom: boolean;
}
